name: Deploy to staging
on:
  push:
    branches:
      - main

jobs:
  redeploy_3_servers:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy everything to the staging servers
        run: |
          echo "${{ secrets.MONOREPO_SSH }}" &> ~/ssh_key
          mkdir -p /home/runner/.ssh
          ls /home/runner/.ssh
          touch /home/runner/.ssh/known_hosts
          echo "${{ secrets.KNOWN_HOSTS }}" &> /home/runner/.ssh/known_hosts
          chmod 700 /home/runner/ssh_key
          ssh -i /home/runner/ssh_key root@157.245.106.119
          echo "sshed in to the remote server"
          cd Deploy-Turborepo
          ls
          git pull origin main 
          npm install
          npm run build
          pm2 restart fe-server
          pm2 restart http-server
          pm2 restart ws-server
